language: cpp

compiler:
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL

script:
  - cmake -DCMAKE_BUILD_TYPE=Debug -G "CodeBlocks - Unix Makefiles" -DOpenCV_DIR=OpenCV-src
#  - cpack --config CPackConfig.cmake